# 시간과 파이토치의 방
### 파이토치 씹어먹기
* 참고: https://tutorials.pytorch.kr/beginner/basics/intro.html

## 1. 텐서 (TENSOR)

* tensor는 array나 matrix와 매우 유사한 특수한 자료구조
* PyTorch에서는 텐서를 사용하여 모델의 입력과 출력, 그리고 모델의 매개변수들을 부호화(encode)

* tensor는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 NumPy의 ndarray와 유사
* tensor는 자동 미분(automatic differentiation)에 최적화되어 있음

In [1]:
import torch
import numpy as np

### Tensor 초기화
* tensor는 여러가지 방법으로 초기화할 수 있음
    1. 데이터로부터 직접 생성하기: 데이터로부터 직접 tensor를 생성할 수 있음. 데이터의 자료형은 자동으로 유추
    
    2. NumPy 배열로부터 생성하기: tensor는 NumPy 배열로 생성할 수 있음. 반대도 가능
    
    3. 다른 tensor로부터 생성하기: 명시적으로 override하지 않는다면, 인자로 주어진 tensor의 속성 (shape, datatype)을 유지

In [2]:
# 1. 데이터로부터 직접 생성하기
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
# 2. NumPy 배열로부터 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# 3. 다른 텐서로부터 생성하기
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씀
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6154, 0.5604],
        [0.7596, 0.7249]]) 



* 무작위(random) 또는 상수(constant) 값을 사용하기
    * shape는 tensor의 dimension을 나타내는 튜플로, 아래 함수들에서는 출력 tensor의 dimension을 결정 **(꼭, shape를 튜플로 만들 필요는 없는 것 같음. 리스트로 만들어서 사용해도 정상적으로 동작)**

In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor} \n')

Random Tensor: 
 tensor([[0.3336, 0.6541, 0.9187],
        [0.3836, 0.8696, 0.5586]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [6]:
shape = [3, 2,]
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor} \n')

Random Tensor: 
 tensor([[0.3242, 0.5013],
        [0.6573, 0.4327],
        [0.6030, 0.5267]]) 

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) 



### Tensor의 속성(Attribute)
* tensor의 속성은 tensor의 shape, datatype 및 어느 장치에 저장되는지를 나타냄

In [7]:
tensor = torch.rand(3, 4)

print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor 연산(Operation)
* 전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등, 100가지 이상의 텐서 연산
    * 참고: https://pytorch.org/docs/stable/torch.html
* 기본적으로 텐서는 CPU에 생성
    * .to 메소드를 사용하면 GPU로 텐서를 명시적으로 이동할 수 있음

In [9]:
# if torch.cuda.is_available():
#     tensor = tensor.to('cuda')

In [10]:
# NumPy식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column: ', tensor[..., -1])

tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


* tensor 합치기는 .cat 메소드
* torch.cat 과 미묘하게 다른 tensor 결합 연산인 torch.stack

In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


* 산술 연산 (Arithmetic operations)

In [15]:
# 두 tensor 간의 행렬 곱을 계산
# y1, y2, y3는 모두 같은 값
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(y1)
print(y2)
print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [17]:
# 요소별 곱 계산
# z1, z2, z3는 모두 같은 값
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


* 단일-요소 (single-element) 텐서
    * tensor의 모든 값을 하나로 집계하여 요소가 하나인 tensor의 경우, item()을 사용하여 python 숫자 값으로 변환할 수 있음

In [18]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


* 바꿔치기 (in-place) 연산
    * 연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, _ 접미사를 갖는다

In [19]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### NumPy 변환 (Bridge)
* CPU 상의 tensor와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다

In [20]:
# tensor를 NumPy 배열로 변환하기
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [21]:
# tensor의 변경 사항이 NumPy 배열에 반영됩니다
t.add_(1)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [23]:
# NumPy 배열을 tensor로 변환하기
n = np.ones(5)
t = torch.from_numpy(n)

print(f'n: {n}')
print(f't: {t}')

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [24]:
# NumPy 배열의 변경 사항이 tensor에 반영됩니다
np.add(n, 1, out=n)
print(f'n: {n}')
print(f't: {t}')

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
